# Generated by Django 4.1 on 2023-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_options_story_author_alter_story_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/stories/covers/'),
        ),
        migrations.AlterModelTable(
            name='story',
            table='Story',
        ),
    ]
