# Generated by Django 4.2.2 on 2023-06-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_cover_picture_alter_story_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='stories/covers/'),
        ),
    ]
