# Generated by Django 4.2.2 on 2023-07-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='preview_content',
            field=models.CharField(default='story preview...', max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=120, unique=True),
        ),
    ]
