# Generated by Django 4.2.2 on 2023-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_story_preview_content_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=120, unique=True),
        ),
    ]
